project:
  type: website
  render:
    - "about.qmd"
    - "research_interests.qmd"
    - "publications.qmd"
    - "current_courses.qmd"
    - "past_courses.qmd"
    - "professional_service.qmd"
    - "contact_info.qmd"
website:
  title: "Kyriakos M. Deliparaschos"
  navbar:
    left:
      - text: About
        href: about.qmd
      - text: Research Interests
        href: research_interests.qmd
      - text: Publications
        href: publications.qmd
      - text: Teaching
        menu:
          - text: Current Courses
            href: current_courses.qmd
          - text: Past Courses
            href: past_courses.qmd
      - text: Professional Service
        href: professional_service.qmd
      - text: Contact Info
        href: contact_info.qmd
format:
  html:
    theme: flatly
    css: styles.css
    toc: true

resources:
    - "/bibtex/publications.bib"
    - "js/bibtex_js.js"


